# Containerfile
FROM registry.access.redhat.com/ubi10/ubi-minimal

LABEL name="haproxy" \
      vendor="Custom" \
      summary="OpenShift-friendly HAProxy on UBI 10" \
      description="HAProxy installed from UBI 10 repositories with arbitrary UID support and fixed config path /etc/haproxy/haproxy.cfg"

ENV HAPROXY_CFG_DIR=/etc/haproxy \
    HAPROXY_CFG_FILE=/etc/haproxy/haproxy.cfg \
    HAPROXY_CONF_D_DIR=/etc/haproxy/conf.d \
    HAPROXY_STATE_DIR=/var/lib/haproxy \
    HAPROXY_RUN_DIR=/var/lib/haproxy \
    HAPROXY_PIDFILE=/var/lib/haproxy/haproxy.pid \
    HAPROXY_CERT_DIR=/etc/haproxy/certs \
    HAPROXY_BACKUP_DIR=/etc/haproxy/backups \
    HAPROXY_MAPS_DIR=/etc/haproxy/maps \
    HAPROXY_SPOE_DIR=/etc/haproxy/spoe \
    HAPROXY_DATAPLANE_STORAGE_DIR=/etc/haproxy/dataplane-storage \
    DATAPLANE_VERSION=3.3.3 \
    DATAPLANE_URL_BASE=https://github.com/haproxytech/dataplaneapi/releases/download \
    HOME=/tmp

RUN set -eux; \
    microdnf -y update; \
    microdnf -y install \
        haproxy \
        findutils \
        procps-ng; \
    curl -fsSL  ${DATAPLANE_URL_BASE}/v${DATAPLANE_VERSION}/dataplaneapi_${DATAPLANE_VERSION}_linux_amd64.rpm -o /tmp/dataplaneapi_linux_amd64.rpm; \
    rpm -ivh /tmp/dataplaneapi_linux_amd64.rpm; \
    rm /tmp/dataplaneapi_linux_amd64.rpm; \
    rpm -q haproxy; \
    microdnf -y update; \
    haproxy -v; \
    microdnf clean all; \
    rm -rf /var/cache/dnf /var/cache/yum /tmp/*; \
    mkdir -p "${HAPROXY_CFG_DIR}" "${HAPROXY_CONF_D_DIR}" "${HAPROXY_STATE_DIR}" "${HAPROXY_CERT_DIR}" "${HAPROXY_BACKUP_DIR}" "${HAPROXY_MAPS_DIR}" "${HAPROXY_SPOE_DIR}" "${HAPROXY_DATAPLANE_STORAGE_DIR}" /run/haproxy /tmp/haproxy /tmp/haproxy-transactions /tmp/spoe-haproxy; \
    chgrp -R 0 "${HAPROXY_CFG_DIR}" "${HAPROXY_STATE_DIR}" "${HAPROXY_CERT_DIR}" "${HAPROXY_BACKUP_DIR}" "${HAPROXY_MAPS_DIR}" "${HAPROXY_SPOE_DIR}" "${HAPROXY_DATAPLANE_STORAGE_DIR}" /run/haproxy /tmp/haproxy /tmp/haproxy-transactions /tmp/spoe-haproxy /tmp; \
    chmod -R g=u "${HAPROXY_CFG_DIR}" "${HAPROXY_STATE_DIR}" "${HAPROXY_CERT_DIR}" "${HAPROXY_BACKUP_DIR}" "${HAPROXY_MAPS_DIR}" "${HAPROXY_SPOE_DIR}" "${HAPROXY_DATAPLANE_STORAGE_DIR}" /run/haproxy /tmp/haproxy /tmp/haproxy-transactions /tmp/spoe-haproxy /tmp; \
    find "${HAPROXY_CFG_DIR}" "${HAPROXY_STATE_DIR}" "${HAPROXY_CERT_DIR}" /run/haproxy /tmp/haproxy -type d -exec chmod g+s {} \;

COPY scripts/ /usr/local/bin/
COPY haproxy.cfg /etc/haproxy/haproxy.cfg
COPY conf.d/ /etc/haproxy/conf.d/
COPY certs/ /etc/haproxy/certs/
COPY dataplaneapi.yaml /etc/haproxy/dataplaneapi.yaml

RUN set -eux; \
    chgrp 0 /usr/local/bin/container-entrypoint.sh \
        /usr/local/bin/haproxy-reload.sh \
        /etc/haproxy/haproxy.cfg \
        /etc/haproxy/dataplaneapi.yaml; \
    chmod 0755 /usr/local/bin/*.sh; \
    chmod 0644 /etc/haproxy/haproxy.cfg; \
    chmod 0640 /etc/haproxy/dataplaneapi.yaml; \
    find /etc/haproxy/conf.d /etc/haproxy/certs -type f -exec chmod 0644 {} \;
EXPOSE 8080 8443 8444 8404

#STOPSIGNAL SIGUSR1
STOPSIGNAL SIGTERM

ENTRYPOINT ["/usr/local/bin/container-entrypoint-dataplane.sh"]
CMD ["-f", "/etc/haproxy/haproxy.cfg", "-f", "/etc/haproxy/conf.d/"]
